// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
........................
..............fff.......
.............f2fffff....
...........ff22eeeeeff..
..........ff222eeeeeeff.
..........feeeefffeeeef.
.........fe2222eeefffff.
.........f2efffff222efff
..cc.....fffeeefffffffff
..cdcc...fee44fbbe44efef
..ccddcc..feddfbb4d4eef.
....cdddceefddddd4eeef..
.....ccdcddee2222222f...
......cccdd44e544444f...
.........eeeeffffffff...
.............ff...fff...
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image2":
            case "myImage0":return img`
........................
..............fff.......
.............f2fffff....
...........ff22eeeeeff..
..........ff222eeeeeeff.
..........feeeefffeeeef.
.........fe2222eeefffff.
.........f2efffff222efff
..cc.....fffeeefffffffff
..cdcc...fee44fbbe44efef
..ccddcc..feddfbb4d4eef.
....cdddceefddddd4eeef..
.....ccdcddee2222222f...
......cccdd44e544444f...
.........eeeeffffffff...
.............ff...fff...
........................
........................
........................
........................
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
